name: Health check

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Scheduled health check
        uses: Jtalk/url-health-check-action@v4
        with:
          url: ${{ vars.WEBSITE_URL }}
          max-attempts: 3
          retry-delay: 5s
